name: NodeJS Webpack Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 22.x, 24.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        corepack enable
        yarn clean || true
        yarn
        yarn lint
        yarn lint:unused-exports
        yarn build:packages
        yarn clean || true
        yarn web:build:prod
        yarn test
        yarn storybook:build
        yarn desktop:build:prod
